language: python

addons:
  postgresql: '9.6'

services:
- postgresql
- redis-server
- docker

python:
- '3.6'

cache:
  pip: true

install:
- pip install -U pip setuptools
- pip install -r py/tests/requirements.txt
- pip install -r py/requirements.txt

script:
- make lint
- make test
- make build

after_success:
- ls -lha
- cp py/setup.cfg .
- bash <(curl -s https://codecov.io/bash)
